name: widget_install
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.13
  permission_handler: ^11.2.0
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
